// Generated by https://quicktype.io

export interface IClientsTypesResponse {
    clientsTypes: IClientsType[];
}

export interface IClientsType {
    id:         number;
    name:       string;
    created_at: string;
    updated_at: string;
}
