// Generated by https://quicktype.io

export interface ICreateClientsResponse {
    message: string;
    clients: Clients;
}

interface Clients {
    id:              string;
    name:            string;
    lastname:        string;
    description:     string;
    clients_type_id: number;
    code:            string;
    exchange_rate:   string;
    slug:            string;
}
